name: wordshk
description: words.hk dictionary for mobile

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_search_bar: 3.0.0-dev.1
  flutter_rust_bridge: ^1.9.1
  path_provider: ^2.0.8
  flutter_html:
    git:
      url: git://github.com/Sub6Resources/flutter_html.git
      ref: ed48ee825a997abfcc1dfe43a98280ce0ea3a39a
  equatable: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  test: ^1.17.10

flutter:
  uses-material-design: true

