name: wordshk
description: words.hk dictionary for mobile

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.3.0

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_rust_bridge: ^1.34.2
  equatable: ^2.0.0
  flutter_native_splash: ^2.0.4
  just_audio: ^0.9.27
  expandable: ^5.0.1
  url_launcher: ^6.1.0
  intl: ^0.17.0
  provider: ^6.0.2
  flutter_portal: ^1.1.0
  flutter_web_browser: ^0.17.1
  shared_preferences: ^2.0.15
  scrollable_positioned_list: ^0.3.2
  scroll_to_index: ^3.0.1
  flutter_tts: ^3.4.0
  audio_session: ^0.1.8
  keyboard_actions: ^4.0.0
  csv: ^5.0.1
  flutter_keyboard_visibility: ^5.2.0
  google_mlkit_digital_ink_recognition: ^0.4.0
  settings_ui: ^2.0.2
  cupertino_icons: ^1.0.5
  flutter_platform_widgets: ^2.0.0
  speech_to_text: ^5.5.0
  introduction_screen: ^3.0.2
  permission_handler: ^10.0.0
#  freezed_annotation: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  test: ^1.17.10
  flutter_launcher_icons: "^0.9.2"
  flutter_launcher_name:
    git:
      url: https://github.com/AlienKevin/flutter_launcher_name
      ref: "0.11.1"
#  build_runner:
#  freezed: ^1.1.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/jyutping_female/
  fonts:
    - family: ChironHeiHK
      fonts:
        - asset: fonts/ChironHeiHK-R.ttf
        - asset: fonts/ChironHeiHK-SB.ttf
          weight: 600

flutter_native_splash:
  color: "ffffff"
  color_dark: "000000"
  image: "assets/icon.png"
  image_dark: "assets/icon_grey.png"
  info_plist_files:
    - 'ios/Runner/Info-Debug.plist'
    - 'ios/Runner/Info-Release.plist'

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon_with_bg.png"

flutter_launcher_name:
  name: "words.hk"
