name: wordshk
description: words.hk dictionary for mobile

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.4.3+19 # Android requires bumping build version (after +)

environment:
  sdk: "^3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_rust_bridge: 2.0.0-dev.4
  equatable: ^2.0.0
  flutter_native_splash: ^2.3.6
  just_audio: ^0.9.35
  expandable: ^5.0.1
  url_launcher: ^6.1.12
  intl: ^0.18.1
  provider: ^6.0.5
  flutter_portal: ^1.1.4
  flutter_web_browser: ^0.17.1
  shared_preferences: ^2.2.0
  scrollable_positioned_list: ^0.3.8
  scroll_to_index: ^3.0.1
  flutter_tts: ^3.8.3
  audio_session: ^0.1.16
  keyboard_actions: ^4.2.0
  csv: ^5.0.2
  flutter_keyboard_visibility: ^5.4.1
  google_mlkit_digital_ink_recognition: ^0.10.0
  settings_ui: ^2.0.2
  cupertino_icons: ^1.0.5
  flutter_platform_widgets: ^6.0.2
  introduction_screen: ^3.1.11
  permission_handler: ^11.1.0
  ffi: ^2.1.0
  path_provider: ^2.1.0
  sqflite: ^2.3.0
  path: ^1.8.3
  draw_on_path: ^0.0.2
  flutter_core_spotlight:
    git:
      url: https://github.com/AlienKevin/flutter_core_spotlight.git
      ref: 500ac5ebb5fc3b88e4e57d64c8c8c645f71980b5
  aws_cognito_identity_api: ^2.0.0
  aws_sqs_api: ^2.0.0
  uuid: ^3.0.7
  flutter_fgbg: ^0.3.0
  device_info_plus: ^9.1.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  rust_builder:
    path: rust_builder

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  test: ^1.17.10
  flutter_launcher_icons: ^0.13.1
  flutter_launcher_name:
    git:
      url: https://github.com/AlienKevin/flutter_launcher_name
      ref: "0.11.1"
  ffigen: ">=8.0.0 <10.0.0"
  sentry_flutter: ^7.13.2
  sentry_dart_plugin: ^1.6.3
  build_runner: ^2.4.7
  json_serializable:
  freezed: ^2.4.5
  integration_test:
    sdk: flutter
  http: ^0.13.1

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/jyutping_female/
    - aws_secrets.json
  fonts:
    - family: ChironHeiHK
      fonts:
        - asset: fonts/ChironHeiHK-Text-R.otf
        - asset: fonts/ChironHeiHK-Text-SB.otf
          weight: 600

flutter_native_splash:
  color: "ffffff"
  color_dark: "000000"
  image: "assets/icon.png"
  image_dark: "assets/icon_grey.png"
  info_plist_files:
    - 'ios/Runner/Info-Debug.plist'
    - 'ios/Runner/Info-Release.plist'

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon_with_bg.png"

flutter_launcher_name:
  name: "words.hk"

sentry:
  upload_debug_symbols: true
  upload_source_maps: true
  upload_sources: true
  # rest of the configs need to be set by running `source set_sentry_env_vars.sh`
