name: wordshk
description: words.hk dictionary for mobile

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 3.3.0+28

environment:
  sdk: "^3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_rust_bridge: ">=2.0.0-dev.11 <2.0.0-dev.12"
  equatable: ^2.0.0
  flutter_native_splash: ^2.3.6
  just_audio: ^0.9.37
  url_launcher: ^6.2.6
  intl: ^0.18.1
  provider: ^6.0.5
  flutter_portal: ^1.1.4
  flutter_web_browser: ^0.17.1
  shared_preferences: ^2.2.0
  audio_session: ^0.1.19
  csv: ^6.0.0
  flutter_keyboard_visibility: ^6.0.0
  google_mlkit_digital_ink_recognition: ^0.10.0
  settings_ui: ^2.0.2
  cupertino_icons: ^1.0.5
  flutter_platform_widgets: ^6.0.2
  introduction_screen: ^3.1.12
  permission_handler: ^11.1.0
  ffi: ^2.1.0
  path_provider: ^2.1.0
  sqflite: ^2.3.3
  path: ^1.8.3
  draw_on_path: ^0.0.2
  aws_cognito_identity_api: ^2.0.0
  aws_sqs_api: ^2.0.0
  uuid: ^4.4.0
  flutter_fgbg: ^0.3.0
  device_info_plus: ^10.1.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  rust_builder:
    path: rust_builder
  go_router: ^13.2.4
  bubble_tab_indicator: ^0.1.6
  scrollview_observer: ^1.19.0
  flutter_svg: ^2.0.9
  package_info_plus: ^6.0.0
  flutter_archive: ^6.0.3
  sentry_flutter: ^8.2.0
  flutter_email_sender: ^6.0.3
  flutter_markdown: ^0.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  test: ^1.17.10
  flutter_launcher_icons: ^0.13.1
  flutter_launcher_name:
    git:
      url: https://github.com/AlienKevin/flutter_launcher_name
      ref: "0.11.1"
  ffigen: ">=8.0.0 <10.0.0"
  build_runner: ^2.4.7
  json_serializable:
  freezed: ^2.4.5
  integration_test:
    sdk: flutter
  http: ^0.13.1

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/jyutping_female/
    - assets/privacy_policy/
  fonts:
    - family: ChironHeiHK
      fonts:
        - asset: fonts/ChironHeiHK-Text-R.otf
        - asset: fonts/ChironHeiHK-Text-SB.otf
          weight: 600

flutter_native_splash:
  color: "ffffff"
  color_dark: "000000"
  image: "assets/icon.png"
  image_dark: "assets/icon_grey.png"
  info_plist_files:
    - 'ios/Runner/Info-Debug.plist'
    - 'ios/Runner/Info-Release.plist'

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon_with_bg.png"

flutter_launcher_name:
  name: "words.hk"

sentry:
  upload_debug_symbols: true
  upload_source_maps: true
  upload_sources: true
  # rest of the configs need to be set by running `source set_sentry_env_vars.sh`
