[package]
name = "wordshk_api"
version = "0.1.0"
edition = "2021"

[dependencies]
wordshk_tools = { git = "https://github.com/AlienKevin/wordshk-tools.git", rev = "9d869f1d115c8f82a3288eba26d5ea35228112b5" }
flutter_rust_bridge = "=1.80.1"
anyhow = { version = "1.0.52", features = ["backtrace"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
parking_lot = "0.12.1"
lazy_static = "1.4.0"
flate2 = "1.0"
#oslog = { version = "0.1.0" }
#log = "0.4.14"
openssl = { version = "*", features = ["vendored"] }
csv = "1.1.6"
rmp-serde = "1.1.2"

[lib]
name = "wordshk_api"
crate-type = ["cdylib", "staticlib"]
