[package]
name = "wordshk_api"
version = "0.1.0"
edition = "2021"

[dependencies]
wordshk_tools = "3.9.8-beta"
flutter_rust_bridge = "1.27.2"
anyhow = { version = "1.0.52", features = ["backtrace"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
parking_lot = "0.11.2"
lazy_static = "1.4.0"
#oslog = { version = "0.1.0" }
#log = "0.4.14"
openssl = { version = "*", features = ["vendored"] }
csv = "1.1.6"

[lib]
name = "wordshk_api"
crate-type = ["cdylib", "staticlib"]
